sudo: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
node_js: "7"
install:
  - pip install -r requirements.txt
  - npm install gitbook-cli -g
  - gitbook install docs
script: 
  - pytest
  - gitbook build docs
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs/_book
  on:
    branch: master
