language: python
python: "3.6"
node_js: "7"
before_install:
  - sudo apt-get install graphviz
install:
  - pip install -r requirements.txt
  - npm install gitbook-cli -g
  - cd docs
  - npm install safe-buffer
  - cd ..
  - gitbook install docs
jobs:
  include:
    - stage: test
      script: pytest
    - stage: build_docs
      script: gitbook build docs
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: docs/_book
stages:
  - test
  - name: build_docs
    if: branch = master